spring:
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: "localhost:29092"
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    consumer:
      group-id: test-order_aggregation-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.DoubleDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    streams:
      application-id: test-app_producer
      cleanup:
        on-startup: true
        on-shutdown: true


kafka:
  stream:
    electronic_order:
      topic: electronic_order
    electronic_aggregation:
      topic: combined_order
